('Full Command: ', './workloads/GAPBS/second_wrapper1 0 8 ./workloads/GAPBS/bin/ ./workloads/GAPBS/bin/bc -f ./workloads/GAPBS/gapbs-data/twitter.sg -i4 -n16')
Traceback (most recent call last):
  File "./workloads/GAPBS/gapbs-wrapper.py", line 51, in <module>
    main(sys.argv[1:])
  File "./workloads/GAPBS/gapbs-wrapper.py", line 47, in main
    subprocess.call(full_cmd) # run converting
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Command exited with non-zero status 1
execution_time 0.29 (s)
